name: Develop

on:
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.1'
      
      - name: Check for Go modules and install dependencies
        run: |
          if [ -f go.mod ]; then
            go mod download
          else
            go get -v ./...
          fi

      - name: Build
        run: go build -v ./...

      - name: Run Tests
        run: go test -coverpkg=./... -race -coverprofile=coverage.out -covermode=atomic ./..

      - name: Check for coverage.out in any directory
        run: |
          found_file=$(find . -name "coverage.out" -print -quit)
          if [ -n "$found_file" ]; then
            echo "coverage.out exists in at least one directory at location: $found_file"
          else
            echo "coverage.out does not exist in any directory"
            # You can add additional debugging information or commands here
          fi
     
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
