name: Deploy Go Program

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.1

      - name: Set up PostgreSQL Environment Variables
        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          echo "DB_NAME=${DB_NAME}" >> $GITHUB_ENV
          echo "DB_USER=${DB_USER}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${DB_PASSWORD}" >> $GITHUB_ENV

      - name: Build Go program
        run: go build -o main

      - name: Use SSH key for deployment
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Debug Loaded SSH Keys
        run: |
          ssh-add -l

      - name: Copy program and migrations to server
        run: |
          scp -o StrictHostKeyChecking=no -i deploy_key.pem ./main $SERVER_USERNAME@$SERVER_IP:/usr/local/go_personal_site
          scp -o StrictHostKeyChecking=no -i deploy_key.pem -r ./database/migrations/ $SERVER_USERNAME@$SERVER_IP:/usr/local/go_personal_site/database
        env:
          SERVER_USERNAME: root
        SERVER_IP: 87.106.122.212
